"""Helper to generate one file that containers can include to mess with the hosts file"""

import logging
from pathlib import Path

from .config import MWConfig

LOGGER = logging.getLogger(__name__)


def generate_hosts_bash_script() -> str:
    """Generate the bash script"""
    cnf = MWConfig.singleton()
    if "localmaeher" not in cnf.domain:
        return "#!/bin/bash \n# Not in localmaeher mode\n"
    script = """#!/bin/bash -l
# Add localmaeher names to hosts file
awk '!/.*localmaeher.*/' /etc/hosts >/etc/hosts.new && cat /etc/hosts.new >/etc/hosts
echo '### Autogenerated localmaeher entries start ###' >>/etc/hosts\n"""
    for name in set([cnf.domain, *cnf.fqdns]):
        script += (
            """echo "$(getent ahostsv4 host.docker.internal | grep DGRAM | awk '{ print $1 }') """
            + name
            + '" >>/etc/hosts\n'
        )
    script += """echo '### Autogenerated localmaeher entries end ###' >>/etc/hosts\n"""
    return script


def write_product_hosts_script(productname: str) -> Path:
    """Write the script to product manifest dir"""
    config = MWConfig.singleton()
    script_path = config.manifests_base / productname / "hosts_script.sh"
    if not script_path.parent.exists():
        LOGGER.error(f"Product {productname} path does not exist")
        return script_path
    script_path.write_text(generate_hosts_bash_script(), encoding="utf-8")
    script_path.chmod(0o754)  # -rwxr-xr--
    LOGGER.info(f"Wrote {script_path}")
    return script_path
